[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "blockchainlib"
path = "src/lib.rs"

[dependencies]
hex = "0.3.2"
time = "0.3.31"
crypto-hash = "0.3.4"
